#!/bin/bash
# This is a main rrconf module which calls other sub-modules.

# Prerequsities
test -z $(type -p) || { echo bash required; exit 1; }
set -e
set -u
source ${RRCONFINC}

test "${RRUID}" -eq 0 || {
        echo "No root account."
        exit 1
} 

# Dependencies
require cronjob
require users
require sshd
