#!/bin/bash
test -z $(type -p) || { echo bash required; exit 1; }
set -e
set -u
source ${RRCONFINC}

test "${RRUID}" -eq 0 || {
        echo "No root account."
        exit 1
} 


# Install httpd
echo "Installing nginx..."
apt -y install nginx
echo "test" > /var/www/html/index.html


# SSHD config
echo "Configuring SSHD..."
tee /etc/ssh/sshd_config <<EOF
Protocol 2
SyslogFacility AUTH
PermitRootLogin no
ChallengeResponseAuthentication no
GSSAPIAuthentication no
GSSAPICleanupCredentials yes
UsePAM yes
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
X11Forwarding no
Subsystem sftp internal-sftp
UseDNS no
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
HostKeyAlgorithms ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,ssh-ed25519,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com
LoginGraceTime 1m
MaxAuthTries 5
StrictModes yes
ClientAliveInterval 300
ClientAliveCountMax 0
AllowTcpForwarding no
GatewayPorts no
X11UseLocalhost yes
AllowAgentForwarding no
PermitUserEnvironment no
PermitTunnel no
LogLevel INFO
PubkeyAuthentication yes
PermitEmptyPasswords no
HostbasedAuthentication no
IgnoreRhosts yes
PasswordAuthentication yes
EOF

systemctl restart sshd
